name: Create Release

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: echo "Running tests"


  create-release-issue:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Parse git_log
        id: parse_git_log
        run: |
          current_tag=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 $current_tag^)
          echo "current_tag=$current_tag" >> $GITHUB_ENV
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "date=$(git log -1 --pretty=format:'%ad')" >> $GITHUB_ENV
      - name: Create Issue From File
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.run-tests.outputs.version }}
          AUTHOR: ${{ steps.parse_git_log.outputs.author }}
          DATE: ${{ steps.parse_git_log.outputs.date }}
        with:
          filename: .github/issue_template.md
          title: ${{ needs.run-tests.outputs.version }}
          labels: release
          assignees: ${{ steps.parse_git_log.outputs.author }}
          body: ${{ steps.parse_git_log.outputs.body }}
        id: create_issue  # <-- Added this to use outputs in the next step
      - name: Update info issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # <-- Token to authenticate the action
          repository: ${{ github.repository }}  # <-- The owner and repo in 'owner/repo' format
          issue-number: ${{ steps.create_issue.outputs.number }}  # <-- The issue number to update
          body: >  # <-- The content of the comment
            This issue was created automatically.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      issue_number: ${{ steps.create_issue.outputs.number }}  # <-- Updated this to reference the correct step
      issue_url: ${{ steps.create_issue.outputs.url }}  # <-- Updated this to reference the correct step

  build:
    needs: create-release-issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install and Build
        run: |
                npm ci
                PUBLIC_URL="/unit-demo-cra" npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
                folder: build

      - name: Comment issue with deploy
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.create-release-issue.outputs.issue_number }}
          body: |
            Deploy №${{ needs.create-release-issue.outputs.issue_number }}
            Deployment link: https://sh0ny-it.github.io/unit-demo-cra/

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ needs.create-release-issue.outputs.issue_number }}
          comment: >
            This issue was closed automatically.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-tag:
    needs: create-release-issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: 'Release ${{ github.run_number }}'
          draft: false
          prerelease: false
  create-release:
    needs: create-release-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: v${{ github.run_number }}
            release_name: 'Release ${{ github.run_number }}'
            draft: false
