name: Create Release Branch and Run Tests
on: [workflow_dispatch, push]
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ github.ref_name }}'

  run-tests:
    name: Run Tests
    needs: create-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Upload unit test report
        uses: actions/upload-artifact@v2
        with:
          name: unit-report
          path: unit-report

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run end-to-end tests
        run: xvfb-run npm run e2e

      - name: Upload end-to-end test report
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

  build:
    name: Create Release
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 'Release ${{ github.ref }}'
          draft: false
          prerelease: false
