name: Create Release Branch and Run Tests
on: [workflow_dispatch, push]
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ github.ref_name }}'

  run-tests:
    name: Run Tests
    needs: create-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Save unit test report
        run: |
          mkdir -p shared-results
          cp unit-report shared-results/unit-report.txt

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run end-to-end tests
        run: xvfb-run npm run e2e

      - name: Save end-to-end test report
        run: |
          mkdir -p shared-results
          cp playwright-report shared-results/playwright-report.txt

  create-release-issue:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v3

      - name: Pull unit test report to env variable
        shell: bash
        run: echo "UNIT_TEST_RESULTS=$(cat shared-results/unit-report.txt)" >> $GITHUB_ENV

      - name: Pull end-to-end test report to env variable
        shell: bash
        run: echo "E2E_TEST_RESULTS=$(cat shared-results/playwright-report.txt)" >> $GITHUB_ENV

      - name: Create or update release issue
        id: create-release-issue
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          TAG_NAME: $GITHUB_REF_NAME
          ACTOR: $GITHUB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_existing: true
          search_existing: all

      - name: Write issue id in file
        id: write-issue-id
        shell: bash
        run: |
          echo "${{ steps.create-release-issue.outputs.number }}" > $GIT_REF_NAME.txt
      - name: Save release issue id for use in other workflows
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}
          path: ${{ github.ref_name }}.txt

  build:
    name: Create Release
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 'Release ${{ github.ref }}'
          draft: false
          prerelease: false
