name: Create Release Branch

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "RELEASE_BRANCH=release-${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b ${{ env.RELEASE_BRANCH }}
          git push origin ${{ env.RELEASE_BRANCH }}
