name: Create Release

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: echo "Running tests"

  create-release-issue:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Parse git_log
        id: parse_git_log
        run: |
          current_tag=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 $current_tag^)
          echo "current_tag=$current_tag" >> $GITHUB_ENV
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV
          echo "author=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "date=$(git log -1 --pretty=format:'%ad')" >> $GITHUB_ENV
      - name: Create Issue From File
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.run-tests.outputs.version }}
          AUTHOR: ${{ steps.parse_git_log.outputs.author }}
          DATE: ${{ steps.parse_git_log.outputs.date }}
        with:
          filename: .github/issue_template.md
          title: ${{ needs.run-tests.outputs.version }}
          labels: release
          assignees: ${{ steps.parse_git_log.outputs.author }}
          body: ${{ steps.parse_git_log.outputs.body }}
      - name: Update info issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create_issue.outputs.number }}
          filename: .github/issue_template.md
          update_existing: true
          search_existing: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      issue_number: ${{ steps.create-release-issue.outputs.number }}
      issue_url: ${{ steps.create-release-issue.outputs.url }}
