name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: release-${{ github.ref_name }}
