name: Run workflow for deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./build

  deploy:
    needs: build-job
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ID token
        id: id_token
        uses: peter-evans/id-token@v2
        with:
          jwt_duration_seconds: 600

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ steps.id_token.outputs.id_token_request_url }}
        with:
          branch: gh-pages
          folder: build
